### ISSUE TITLE
Please add adapter testing

### ISSUE THREAD

**Issue by Apollon77** [instalator/ioBroker.vis-players#10]

**Comment by instalator** [comment]
Does not work

**Comment by Apollon77** [comment]
You also need to add the test "scripts" entries in your package.json ... they are missing

**Comment by instalator** [comment]
> You also need to add the test "scripts" entries in your package.json ... they are missing

Does not work

**Comment by Apollon77** [comment]
yes because unit and integration testing makes mo sense for a widget adapter :-) So test in general (make sure npm install works) and the apckage tests are sufficient

**Comment by Apollon77** [comment]
Then just change that the integration tests are run in travis and disabled them by removing https://github.com/instalator/ioBroker.vis-players/blob/master/.travis.yml#L24 or such

**Comment by instalator** [comment]
I do not understand what needs to be done

**Comment by Apollon77** [comment]
Travis fails at this command: https://travis-ci.org/github/instalator/ioBroker.vis-players/jobs/689103740#L421

As told above these tests (unit and integration) make no sense for a vis widget, so also remove https://github.com/instalator/ioBroker.vis-players/blob/master/.travis.yml#L23

**Comment by instalator** [comment]
Happened
